### ISSUE TITLE
DNS inconsistent about zone names

### ISSUE THREAD

**Issue by kdienes** [Hadron/carthage_aws#4]
AwsHostedZone finds it with trailing '.' but AwsDnsManagement expects it not to have one.

I tossed

`if self.name.endswith('.'): self.name = self.name[:-1]`

into my local copy and it works but I'll let someone familiar with the AWS setup tell me the best approach

**Comment by srak289** [comment]
I'm thinking of adding something like AwsHostedZone.contains(name : str) => bool.
I haven't gotten around to pushing what I was working on yet but that fix definitely meets the intent.
I do think that having a contains method would be better so we can take the namefilter logic out of AwsDnsManagement.

**Comment by hartmans** [comment]
I don't quite understand the issue report.
What I can say is that model names in Carthage should not typically have
a trailing dot.
