### ISSUE TITLE
AwsManaged and dict mobs

### ISSUE THREAD

**Issue by srak289** [Hadron/carthage_aws#8]
Some objects in EC2 are not presented as Resources, so one must use the client API calls to present similar behavior to a mob. One of the recent examples is the Transit Gateway. I have found it necessary in these instances to override several methods from AwsManaged.

The format is like so:

name_of_thing = 'transit_gateway'

class Aws{name_of_thing_formatted}(AwsManaged):
    def do_create():
        self.client.create_{name_of_thing}()
    def find_from_name():
        self.client.describe_{name_of_thing}s()
    def do_action():
        self.client.action_{name_of_thing}()
        
I was initially thinking about something like getattr(client, f'action_{name_of_thing}').__call__(**kwargs) but I think there is a more elegant way to do this..with something like a factory pattern.

**Comment by hartmans** [comment]
Okay, so perhaps something like `AwsManagedNoResource` (let's find a better name) that
* has a find_from_id that looks up the issue based on `getattr(client, f'describe_{self.resource_type')` or similar
* probably open codes do_create.  While you might be able to look up the create method, finding the parameters is going to be specific to what you're doing; doing a good job of modeling is almost certainly going to require you to open code that
* possibly has easy ways to get accessors into the self.mob dict for common attributes
* provides delete based on `getattr(client, f'delete_{self.resource_type}')
*  provides a better mechanism to get the right client to use
Is that sort of what you're thinking of?

**Comment by hartmans** [comment]
Is this still useful?  I think we've had a number of objects that did not use the service_resource pattern, but appear to use AwsManaged without too much pain. Examples include transit gateways, nat gateways and route53 zones.

**Comment by srak289** [comment]
I think this issue has aged beyond relevance.
